services:
  jupyter:
    build: .
    ports:
      - "127.0.0.1:8118:8118"
    working_dir: /work
    command: sh -c "cd /work && npm install && jupyter server --ServerApp.token='' --ServerApp.password='' --ip=0.0.0.0 --port=8118 --no-browser"
    volumes:
      - ./:/work
    environment:
      FORCE_COLOR: "3"
